services:
  # Base de Datos PostgreSQL para todos los servicios
  db:
    image: postgres:14-alpine
    container_name: 1start-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=1start_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # La aplicación web principal - AHORA CORREGIDO
  platform:
    container_name: 1start-platform
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/1start_dev
      - NEXTAUTH_URL=http://localhost:3000

volumes:
  postgres_data: